repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-json
    - id: check-added-large-files
    - id: detect-private-key
    - id: check-executables-have-shebangs
    - id: check-symlinks
    - id: detect-aws-credentials
    - id: no-commit-to-branch
      args: [--branch, master]
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
