# serverless.yml
service: birthday-app

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: src/app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: eu-west-1

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'GET /'
      - http: 'PUT /'
