# action.yaml
name: 'Run app.py'
description: 'A GitHub Action that will run app.py and test it'
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Run app.py
      id: run-app
      run: python app.py
      shell: bash