# .github/workflows/test_action.yaml
name: Python app.py test
on: [push, pull_request]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Runs application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  
      - name: Install Dependencies
        run: pip install -r requirements.txt
        shell: bash

